{
  pkgs,
  lib,
  config,
  ...
}:
{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."superproductivity-app" = {
    image = "johannesjo/super-productivity:latest";
    environment = {
      "IS_COMPRESSION_ENABLED" = "true";
      "IS_ENCRYPTION_ENABLED" = "false";
      "SYNC_INTERVAL" = "15";
      "WEBDAV_BASE_URL" = "https://webdav.nuc.lab";
      "WEBDAV_SYNC_FOLDER_PATH" = "super-productivity";
      "WEBDAV_USERNAME" = "super-productivity";
    };
    ports = [
      "3002:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=superproductivity_default"
    ];
  };

  systemd.services."podman-superproductivity-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-superproductivity_default.service"
    ];
    requires = [
      "podman-network-superproductivity_default.service"
    ];
    partOf = [
      "podman-compose-superproductivity-root.target"
    ];
    wantedBy = [
      "podman-compose-superproductivity-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-superproductivity_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f superproductivity_default";
    };
    script = ''
      podman network inspect superproductivity_default || podman network create superproductivity_default
    '';
    partOf = [ "podman-compose-superproductivity-root.target" ];
    wantedBy = [ "podman-compose-superproductivity-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-superproductivity-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
