{
  config,
  pkgs,
  lib,
  ...
}:

{
  # options.kiosk.enable = lib.mkEnableOption "Minimal kiosk browser setup";
  # config = lib.mkIf config.kiosk.enable {
  # };

  # edit the .xinitrc here
  environment.etc."xinitrc-kiosk".text = ''
    #!/bin/env bash

    # THIS FILE IS GENERATED BY NIXOS AND WILL BE RESET ON REBUILD
    # EDIT THIS FILE IN THE kiosk.nix MODULE
    # TEMPORARY CHANGES CAN STILL BE DONE

    matchbox-window-manager &
    luakit
  '';

  services.xserver.enable = true;
  services.xserver.displayManager.startx.enable = true;

  environment.systemPackages = with pkgs; [
    luakit
    matchbox
    xorg.xinit
    xbanish
  ];

  # (optional) Set X11 DPI or scaling for old Mac display
  # services.xserver.dpi = 96;

  system.activationScripts.kioskXinitrc = {
    text = ''
      targetUser="max"
      homeDir=$(eval echo ~"$targetUser")

      if [ -d "$homeDir" ] ; then
        echo "Installing .xinitrc for user $targetUser"
        install -Dm755 /etc/xinitrc-kiosk "$homeDir/.xinitrc"
        chown "$targetUser:users" "$homeDir/.xinitrc"
      fi
    '';
  };
}
