keys:
  # native age user key
  - &max age168p6tecclghkhu2c2swvtqhufnk87tngtsvcgng6n7w62j4yd9hsjwz4fp
  # host ssh keys
  - &yoga age12hhwf7vqzc4ct5u0zxpnf0jrgdazhpwzpkq405f5hcjdk8gle4jqj7czvx
  - &nuc age1tzxvzx8kqvpaklsvulyr7phjqqtevjhxtyvz93qz67upnuam9qjs3dmrej

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *max
          - *yoga
          - *nuc
  - path_regex: secrets/.+\.p12(\.enc)?$
    key_groups:
      - age:
          - *max
          - *yoga
stores:
  json:
    indent: 2
  json_binary:
    indent: 2
